In [28]:
import pandas as pd
ds=pd.read_csv(r'C:\Users\91739\Downloads\Bipolar.csv')
ds.head()

,ID,Felt alone,felt stressed,feeling sad,being myself,hard to have fun,easily annoyed,short temper,freq anger,lose temper,...,Stomach pain,Back pain,joint pains,expect awful,felt worried,felt nervous,scared easily,worried away from home.,Gender,Age
0,1,3,3,3,4,4,3,5,5,3,...,3,3,3,3,4,5,3,4,Female,14
1,2,3,3,3,3,4,5,5,1,3,...,5,1,5,3,4,4,3,4,Female,14
2,3,5,3,1,3,3,1,3,5,3,...,3,1,5,1,4,5,5,4,Female,14
3,4,1,1,1,1,1,1,5,3,3,...,1,1,1,1,1,3,4,4,Female,13
4,5,3,4,3,3,3,5,3,1,3,...,3,5,1,5,5,5,5,4,Female,14

In [29]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ID                       33 non-null     int64
 1   Felt alone               33 non-null     int64
 2   felt stressed            33 non-null     int64
 3   feeling sad              33 non-null     int64
 4   being myself             33 non-null     int64
 5   hard to have fun         33 non-null     int64
 6   easily annoyed           33 non-null     int64
 7   short temper             33 non-null     int64
 8   freq anger               33 non-null     int64
 9   lose temper              33 non-null     int64
 10  irritability             33 non-null     int64
 11  qnconfident              33 non-null     int64
 12  qnsleep                  33 non-null     int64
 13  qntalk                   33 non-null     int64
 14  thoughts duration        33 non-null     int64
 15  bothering                33 non-null     int64
 16  thoughts control         33 non-null     int64
 17  interference             33 non-null     int64
 18  restless sleep           33 non-null     int64
 19  sleepsatisfaction        33 non-null     int64
 20  refreshment              33 non-null     int64
 21  diff fall sleep          33 non-null     int64
 22  sleep quality            33 non-null     int64
 23  Stomach pain             33 non-null     int64
 24  Back pain                33 non-null     int64
 25  joint pains              33 non-null     int64
 26  expect awful             33 non-null     int64
 27  felt worried             33 non-null     int64
 28  felt nervous             33 non-null     int64
 29  scared easily            33 non-null     int64
 30  worried away from home.  33 non-null     int64
 31  Gender                   33 non-null     object
 32  Age                      33 non-null     int64
dtypes: int64(32), object(1)
memory usage: 8.6+ KB

In [30]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
ds['Gender']=le.fit_transform(ds['Gender'])
ds['Gender']=pd.DataFrame(ds['Gender'])

In [31]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ID                       33 non-null     int64
 1   Felt alone               33 non-null     int64
 2   felt stressed            33 non-null     int64
 3   feeling sad              33 non-null     int64
 4   being myself             33 non-null     int64
 5   hard to have fun         33 non-null     int64
 6   easily annoyed           33 non-null     int64
 7   short temper             33 non-null     int64
 8   freq anger               33 non-null     int64
 9   lose temper              33 non-null     int64
 10  irritability             33 non-null     int64
 11  qnconfident              33 non-null     int64
 12  qnsleep                  33 non-null     int64
 13  qntalk                   33 non-null     int64
 14  thoughts duration        33 non-null     int64
 15  bothering                33 non-null     int64
 16  thoughts control         33 non-null     int64
 17  interference             33 non-null     int64
 18  restless sleep           33 non-null     int64
 19  sleepsatisfaction        33 non-null     int64
 20  refreshment              33 non-null     int64
 21  diff fall sleep          33 non-null     int64
 22  sleep quality            33 non-null     int64
 23  Stomach pain             33 non-null     int64
 24  Back pain                33 non-null     int64
 25  joint pains              33 non-null     int64
 26  expect awful             33 non-null     int64
 27  felt worried             33 non-null     int64
 28  felt nervous             33 non-null     int64
 29  scared easily            33 non-null     int64
 30  worried away from home.  33 non-null     int64
 31  Gender                   33 non-null     int32
 32  Age                      33 non-null     int64
dtypes: int32(1), int64(32)
memory usage: 8.5 KB

In [32]:
import pandas as pd
import matplotlib.pyplot as mp
cols=ds.iloc[0:32]
ds = pd.DataFrame(ds, columns=cols)
y=ds.iloc[:,1:30]
# plot the dataframe
ds.plot(x="ID", y=y, kind="bar", figsize=(9, 8))
 
# print bar graph
mp.show()

ValueError: Index data must be 1-dimensional

In [33]:
cols=ds.iloc[0:32]

In [34]:
cols

,ID,Felt alone,felt stressed,feeling sad,being myself,hard to have fun,easily annoyed,short temper,freq anger,lose temper,...,Stomach pain,Back pain,joint pains,expect awful,felt worried,felt nervous,scared easily,worried away from home.,Gender,Age
0,1,3,3,3,4,4,3,5,5,3,...,3,3,3,3,4,5,3,4,0,14
1,2,3,3,3,3,4,5,5,1,3,...,5,1,5,3,4,4,3,4,0,14
2,3,5,3,1,3,3,1,3,5,3,...,3,1,5,1,4,5,5,4,0,14
3,4,1,1,1,1,1,1,5,3,3,...,1,1,1,1,1,3,4,4,0,13
4,5,3,4,3,3,3,5,3,1,3,...,3,5,1,5,5,5,5,4,0,14
5,6,1,1,1,3,5,5,3,5,5,...,1,1,3,1,3,3,5,3,0,13
6,7,4,4,3,3,4,3,5,5,3,...,3,1,3,4,4,3,4,1,0,13
7,8,3,3,3,3,3,5,5,3,3,...,3,5,3,5,3,3,3,3,0,14
8,9,1,1,1,3,3,1,1,1,1,...,3,3,1,1,1,1,1,5,0,13
9,10,1,3,1,3,4,1,1,1,1,...,1,1,1,3,1,3,3,1,1,13
10,11,1,3,1,4,3,1,1,1,1,...,1,1,1,1,3,1,3,3,1,14
11,12,4,5,5,4,3,5,5,5,5,...,3,5,3,3,5,4,5,3,1,14
12,13,1,1,1,1,1,1,5,5,5,...,1,1,1,3,1,3,3,1,1,13
13,14,1,1,1,1,5,1,1,1,1,...,1,1,1,4,3,3,4,1,1,14
14,15,1,3,3,3,3,1,3,1,1,...,3,1,1,1,1,1,3,3,1,14
15,16,1,1,1,3,1,1,3,1,1,...,1,1,1,3,3,1,3,4,1,13
16,17,5,4,4,3,3,3,1,3,5,...,1,5,3,3,5,5,3,1,1,15
17,18,5,4,4,3,3,1,5,5,5,...,5,5,5,4,3,1,1,1,1,14
18,19,5,3,4,1,3,3,5,3,3,...,1,1,1,3,1,3,1,1,1,14
19,20,3,4,3,3,1,3,1,1,1,...,1,3,3,4,4,3,1,4,1,14
20,21,3,4,1,1,3,1,1,3,5,...,1,1,3,1,1,3,3,5,1,15
21,22,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,4,1,14
22,23,1,1,3,3,4,1,3,1,1,...,1,1,1,3,3,3,3,4,1,15
23,24,1,1,1,3,1,1,1,1,1,...,1,1,1,1,1,3,3,1,1,14
24,25,3,1,4,1,1,5,5,5,5,...,5,1,1,3,1,3,5,5,0,15
25,26,3,4,3,4,1,5,5,3,5,...,1,1,1,1,3,3,3,3,1,15
26,27,3,1,1,4,3,3,5,3,3,...,1,1,3,3,1,3,1,1,1,14
27,28,3,3,3,3,5,3,3,3,3,...,1,1,3,3,3,3,4,4,1,15
28,29,5,3,3,3,1,1,3,1,3,...,3,5,5,3,3,4,3,5,0,16
29,30,3,3,3,4,3,3,3,1,1,...,5,3,5,3,5,5,5,5,0,18
30,31,5,5,4,4,3,3,3,3,3,...,3,3,3,5,5,4,4,4,0,17
31,32,3,4,3,5,1,1,3,3,3,...,1,3,1,4,4,3,1,3,0,18